spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/real_world
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    format_sql: true
  flyway:
    # ??Flyway
    enabled: true
    # ???? flyway_schema_history ?? metadata ?? ??? flyway migrate ????, ????? flyway baseline ??
    baseline-on-migrate: true
    table: card_flyway_history_table
    # flyway ? clean ??????? schema ???? table, ????????????? false ???????????????
#    clean-disabled: true
#    locations: classpath:db/migration
