spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/real_world
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
  flyway:
    # ??Flyway
    enabled: true
    # ????????Flyway??????????Baseline??
    baseline-on-migrate: true
    # history table name
    table: card_flyway_history_table
    # flyway ? clean ??????? schema ???? table, ????????????? false ???????????????
    clean-disabled: true
